"""empty message

Revision ID: 915b720ec1e4
Revises: 214e1e41f8f8
Create Date: 2023-06-29 22:56:53.511425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915b720ec1e4'
down_revision = '214e1e41f8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
