version: '3.8'
services:
  flask-app:
    build: .
    image: python:cors
    command: python manage.py run --host=0.0.0.0 --port=5001
    environment:
      - FLASK_APP=manage.py
      - REACT_APP_API_URL=http://127.0.0.1:5001/api/v1
    ports:
      - 5001:5001
  